import Head from "next/head";
import Appointments from "../components/Appointments";
export default function Home() {
  return (
    <>
      <Head>
        <title>Book Appointment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Appointments />
      </main>
    </>
  );
}
