import React from "react";
import Head from "next/head";
import Confirmation from "@/components/BookAnAppointment/Confirmation";

function ThankYou() {
  return (
    <>
      <Head>
        <title>Confirmation page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Confirmation />
      </main>
    </>
  );
}

export default ThankYou;
